### ISSUE TITLE
Pico ethernet

### ISSUE THREAD

**Issue by g6hfs** [g4eml/PicoTuner#1]
Hi,

Is there any firmware info on ethernet port usage please.

Brian

**Comment by g4eml** [comment]
Ethernet is not yet fully supported by my firmware. The Ethernet branch is experimental only and not for release. Brian G4EWJ is developing firmware using the ethernet port.  This is still in the early stages of testing. You would need to talk to him about that. Maybe in the future we will produce a combined firmware. Colin. On 5 Apr 2024 10:12, g6hfs ***@***.***> wrote:
Hi,
Is there any firmware info on ethernet port usage please.
Brian
